name: Issue Report(RNG)
description: File a Issue report
title: "[RNG- ]: "
labels: ["verification", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: "# TEST 111"
  - type: markdown
    attributes:
      value: "TEST TEST 123"
  - type: textarea
    id: Describe-the-Issue
    attributes:
      label: Describe the Issue
      description: Description of what the issue is
    validations:
      required: true
  - type: markdown
    attributes:
      value: "# Reproduce"
  - type: textarea
    id: RTLVersion
    attributes:
      label: "### RTL Version"
