name: Issue Report(RNG)
description: File a Issue report
title: "[RNG- ]: "
labels: ["verification", "triage"]
assignees:
  - octocat
body:
  - type: textarea
    id: Describe-the-Issue
    attributes:
      label: Describe the Issue
      description: Description of what the issue is
    validations:
      required: true
  - type: dropdown
    id: RTL-version
    attributes:
      label: RTL Version 
      description: What version of our software are you running?
      options:
        - 1.11 (Default)
        - 1.12
        - 1.13
        - 1.14
        - 1.15
        - 1.16
        - 2.0
        - 2.1
        - 2.2
        - 2.3
        - 2.4
        - 2.5
        - 2.6
        - 2.7
        - 2.8
        - 2.9
        - 2.10
    validations:
      required: true
  - type: textarea
    id: Reproduce
    attributes:
      label: To Reproduce
      multiple: true
      options:
        - DV Version
        - Run Script
        - Waveform path
        - Log path
