name: Issue Report(RNG)
description: File a Issue report
title: "[RNG- ]: "
labels: ["verification", "triage"]
assignees:
  - octocat
body:
  - type: textarea
    id: Describe-the-Issue
    attributes:
      label: Describe the Issue
      description: Description of what the issue is
    validations:
      required: true
  - type: textarea
    id: Reproduce
    attributes:
      label: To Reproduce
      value: |
        RTL Version :
        DV Version :
        Run Script :
        Waveform Path :
        Log Path :
        
