name: Issue Report(RNG)
description: File a Issue report
title: "[RNG- ]: "
labels: ["verification", "triage"]
assignees:
  - octocat
body:
  - type: textarea
    id: Describe-the-Issue
    attributes:
      label: Describe the Issue
      description: Description of what the issue is
      value: |
        1. RTL Block Name ::
        2. Description ::
    validations:
      required: true
  - type: markdown
    attributes:
      value: "# Reproduce"
  - type: textarea
    id: RTLVersion
    attributes:
      label: RTL Version
    validations:
      required: true
  - type: textarea
    id: DVEnv
    attributes:
      label: DV Version
  - type: textarea
    id: RunScript
    attributes:
      label: Run Script
  - type: textarea
    id: WaveformPath
    attributes:
      label: Waveform/Log Path
    validations:
      required: true
  
