name: Issue Report(RNG)
description: File a Issue report
title: "[RNG- ]: "
labels: ["verification", "triage"]
assignees:
  - octocat
body:
  - type: textarea
    id: Describe the Issue
    attributes:
      label: Describe the Issue
      description: Description of what the issue is
    validations:
      required: true
  - type: dropdown
    id: RTL version
    attributes:
      label: RTL Version
      description: What version of our software are you running?
      options:
        - 1.11 (Default)
        - 1.12 (Edge)
        - 1.13 (Edge)
        - 1.14 (Edge)
        - 1.15 (Edge)
        - 1.16 (Edge)
        - 2.0 (Edge)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
